<a href="https://colab.research.google.com/github/SLMath/Study_MachileLearning/blob/main/pca_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import datasets
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

import pandas as pd

# import some data to play with
iris = datasets.load_iris()
iris_df = pd.DataFrame(iris.data, columns= iris.feature_names)

ss = StandardScaler()
iris_df.loc[:,:] = ss.fit_transform(iris_df)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [ ]:
iris_df.corr()

sepal length (cm)  ...  petal width (cm)
sepal length (cm)           1.000000  ...          0.817941
sepal width (cm)           -0.117570  ...         -0.366126
petal length (cm)           0.871754  ...          0.962865
petal width (cm)            0.817941  ...          1.000000

[4 rows x 4 columns]

In [ ]:
pca = PCA(n_components= 0.8, svd_solver= 'full')
iris_pca = pca.fit_transform(iris_df)
iris_pca = pd.DataFrame(iris_pca, columns= [f'c{num}' for num in range(1,3)])
iris_pca

c1        c2
0   -2.264703  0.480027
1   -2.080961 -0.674134
2   -2.364229 -0.341908
3   -2.299384 -0.597395
4   -2.389842  0.646835
..        ...       ...
145  1.870503  0.386966
146  1.564580 -0.896687
147  1.521170  0.269069
148  1.372788  1.011254
149  0.960656 -0.024332

[150 rows x 2 columns]

In [ ]:
iris_pca.corr()

c1            c2
c1  1.000000e+00  1.842693e-16
c2  1.842693e-16  1.000000e+00

In [ ]:
pca.components_

array([[ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654],
       [ 0.37741762,  0.92329566,  0.02449161,  0.06694199]])

In [ ]:
import numpy as np
np.sum(np.dot(iris_df, pca.components_.T) - iris_pca)

c1   -3.290875e-13
c2   -3.681049e-13
dtype: float64

In [ ]:
pca.explained_variance_

array([2.93808505, 0.9201649 ])

In [ ]:
pca.explained_variance_ratio_, sum(pca.explained_variance_ratio_)

(array([0.72962445, 0.22850762]), 0.9581320720000165)

In [ ]:
pca.singular_values_

array([20.92306556, 11.7091661 ])

In [ ]:
np.linalg.norm(iris_pca, axis= 0)

array([20.92306556, 11.7091661 ])